<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Beranda_hamburger</name>
   <tag></tag>
   <elementGuidId>9620d829-7740-4262-a7a1-83410966fdf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hamburger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='hamburger']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5845864c-a7b7-4df1-8978-d6c0bdfd5994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hamburger</value>
      <webElementGuid>1cfea2b6-2cbf-4493-84ca-ec7b2b7d12ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hamburger</value>
      <webElementGuid>b31436fe-2127-4a17-ab3b-478b64bbbd12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d6961747-878e-42fb-9b44-165880742da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block absolute right-4 lg:hidden</value>
      <webElementGuid>0ecc1239-692e-47cb-8ded-268652bf8dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hamburger&quot;)</value>
      <webElementGuid>1884e927-2aad-424e-94f1-0ac03a894643</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='hamburger']</value>
      <webElementGuid>f847be20-8ce5-4091-aa98-4a4ec3f79a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/header/div/div/div[2]/button</value>
      <webElementGuid>786d8d90-8a4f-4166-9d80-a5cf8e6f0ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[1]/preceding::button[1]</value>
      <webElementGuid>be5a4065-834e-4f94-b359-7b4c80e75731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluar'])[1]/preceding::button[1]</value>
      <webElementGuid>da2c538d-9f75-434b-8fbe-b06af1141b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>496d0a8f-641c-48d9-85c6-01df61b45253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'hamburger' and @name = 'hamburger' and @type = 'button']</value>
      <webElementGuid>719320e2-dc70-4e90-bfaa-c4db6e669a19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
