<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>18, armada mpv</name>
   <tag></tag>
   <elementGuidId>4ed234d3-9005-4192-8903-9726e00cd944</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[3]/div/div/div[2]/label[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f4665c63-c7ad-4b20-b722-d1a2eae34571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>plan-content insurance p-3 flex items-center mt-3</value>
      <webElementGuid>0b153a8b-a29d-4748-b87e-7de605be4c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mpv175 x 100 x 85 Berat Max 300kg </value>
      <webElementGuid>1bcb7780-5739-4f9e-ab05-1594fad597dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;fixed top-0 left-0 right-0 z-50 p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full justify-center flex&quot;]/div[@class=&quot;relative w-full max-w-lg max-h-full&quot;]/div[@class=&quot;relative bg-white rounded-2xl shadow dark:bg-gray-700&quot;]/div[@class=&quot;p-6 pt-0 scroll-content-modal&quot;]/label[@class=&quot;plan&quot;]/div[@class=&quot;plan-content insurance p-3 flex items-center mt-3&quot;]</value>
      <webElementGuid>26a55e27-715f-46da-ad33-5ed5f1168e7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div/div[2]/label[2]/div</value>
      <webElementGuid>b6266b79-10f2-41f7-905b-34386dd9b9be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berat Max 40kg'])[1]/following::div[1]</value>
      <webElementGuid>988778dc-1ffd-464d-9dc5-5e5b5fb05368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bike'])[1]/following::div[3]</value>
      <webElementGuid>d84fc1ce-f5f6-4af8-855b-43541eb5f7aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/div</value>
      <webElementGuid>673ed3b4-9712-4155-9484-ef9e2001b910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'mpv175 x 100 x 85 Berat Max 300kg ' or . = 'mpv175 x 100 x 85 Berat Max 300kg ')]</value>
      <webElementGuid>ec9204d6-fbb1-4cf4-930a-a7c46873d5c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
