<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>20.Pilih Mitra</name>
   <tag></tag>
   <elementGuidId>49dc8152-b123-4053-a213-1254e32f3547</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div[8]/div[2]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9da5b3b5-2555-434c-8134-3b587caf4cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-3 rounded-lg border border-gray-200 bg-white flex items-center cursor-pointer</value>
      <webElementGuid>6ebd6f67-5be9-469a-ac1c-ca13a4f09ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-target</name>
      <type>Main</type>
      <value>tooltip-animation</value>
      <webElementGuid>ea687efa-70f5-49b5-8967-c47424e061e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Silahkan Pilih Mitra</value>
      <webElementGuid>5930e2d3-3813-43a9-9a7d-36fadc382ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;mt-content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;bg-white shadow-custom px-8 py-8 rounded-2xl -top-20 lg:-top-14 relative z-10&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;w-1/2 mt-8&quot;]/div[@class=&quot;border border-gray-100 rounded-xl&quot;]/div[@class=&quot;p-4&quot;]/div[@class=&quot;p-3 rounded-lg border border-gray-200 bg-white flex items-center cursor-pointer&quot;]</value>
      <webElementGuid>8b4edd5e-673a-4d54-b719-8a1c83dbc43b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div[8]/div[2]/div/div[2]/div</value>
      <webElementGuid>3d52452b-19db-4a3b-9b4d-7c12c72ca3a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[10]/following::div[1]</value>
      <webElementGuid>5b84adc1-e0a3-44a0-8faf-f912a14fe848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Metode Pengiriman'])[1]/preceding::div[3]</value>
      <webElementGuid>1056268e-7c54-4149-8143-f50ae92d9a00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/div[2]/div</value>
      <webElementGuid>7ddb9c94-6fe2-4817-ac46-a5dbc8c742e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Silahkan Pilih Mitra' or . = 'Silahkan Pilih Mitra')]</value>
      <webElementGuid>e0922bdd-066c-465e-89d4-dc3c68229505</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
