<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>8.button_Tambah Barang</name>
   <tag></tag>
   <elementGuidId>01518904-5ff7-4bd3-8f8c-ba9b24a570f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div[4]/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>59071a1d-0860-4ad7-9924-553a614a4914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-target</name>
      <type>Main</type>
      <value>tooltip-default</value>
      <webElementGuid>dae10d97-0b77-49c9-9135-ad4a3ed5ee6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white bg-greenPrimary font-medium rounded-md text-xs px-6 py-2 text-center focus:outline-none disabled:opacity-40</value>
      <webElementGuid>7ec511fe-bfd5-4680-af5f-cd9d98ba44be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tambah Barang </value>
      <webElementGuid>f125d1bd-b52b-4d4d-8ed8-688e628fbecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;mt-content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;bg-white shadow-custom px-8 py-8 rounded-2xl -top-20 lg:-top-14 relative z-10&quot;]/div[@class=&quot;border border-gray-100 rounded-xl mt-6&quot;]/div[@class=&quot;p-4 rounded-t-xl text-[16px] font-medium bg-gray-100 flex items-center&quot;]/div[@class=&quot;ms-auto&quot;]/button[@class=&quot;text-white bg-greenPrimary font-medium rounded-md text-xs px-6 py-2 text-center focus:outline-none disabled:opacity-40&quot;]</value>
      <webElementGuid>577a03c2-1833-4bb2-b35e-42aa55e4ef2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div[4]/div/div/button</value>
      <webElementGuid>7805a520-19e6-4c50-b345-6264bcbe460f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::button[1]</value>
      <webElementGuid>889d9d76-0f4b-4967-9ad9-03b07927949b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Barang Kosong'])[1]/preceding::button[1]</value>
      <webElementGuid>8d6dd1f1-b539-4781-95b2-8ad9113b55a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Penerima'])[1]/preceding::button[1]</value>
      <webElementGuid>2a25391d-3031-468e-90be-194c2ee76e92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tambah Barang']/parent::*</value>
      <webElementGuid>8bb06f01-f106-4b79-a399-d4073cafbbf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/button</value>
      <webElementGuid>3f97c830-7245-4cf7-9197-7608ad91b9da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Tambah Barang ' or . = ' Tambah Barang ')]</value>
      <webElementGuid>c45697dd-a85a-4007-84e1-492b765c602c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
