<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input email</name>
   <tag></tag>
   <elementGuidId>f033823a-8833-4421-b82a-666d0e7aae82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2205a0ca-7a86-4a93-819f-81b481be028d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>2f358d28-0de6-4d5c-af53-8e531d76946f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pl-3 outline-none border-none focus:ring-0 w-full</value>
      <webElementGuid>4fe1fb0d-ab5c-4422-bec7-60043b3f4e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Email</value>
      <webElementGuid>7f27dd70-100c-40d2-b3a9-2780937b2b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>3b815ee2-61e0-4d30-ae8e-f71387e22f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;h-screen lg:flex items-center mt-20 lg:mt-0&quot;]/div[@class=&quot;md:w-[100%] lg:w-2/3 items-center bg-white lg:px-24 px-4&quot;]/form[@class=&quot;bg-white mt-7&quot;]/div[@class=&quot;flex items-center border-2 py-1 px-4 rounded-full w-full&quot;]/input[@class=&quot;pl-3 outline-none border-none focus:ring-0 w-full&quot;]</value>
      <webElementGuid>b8667d26-ed6d-4405-98e6-5318e6de0826</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>d6fb24c2-2089-45fe-b010-91c93453b706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/form/div/input</value>
      <webElementGuid>7d12c63a-5fa4-40ab-bb91-892eaa73eb91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f71ce3e2-83e5-4110-a299-a8530a33ca41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @placeholder = 'Masukkan Email' and @name = 'email']</value>
      <webElementGuid>51b592d2-1485-458e-b76c-31eb31824e58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
